apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nittfest
  labels:
    app: frontend
    app.kubernetes.io/part-of: nittfest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: anshul8394/frontend:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
