apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: nittfest
  labels:
    app: frontend
    app.kubernetes.io/part-of: nittfest
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
