apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: nittfest
  labels:
    app: order-service
    app.kubernetes.io/part-of: nittfest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: anshul8394/order-service:latest
          ports:
            - containerPort: 8082
              protocol: TCP
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
