apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: nittfest
  labels:
    app: user-service
    app.kubernetes.io/part-of: nittfest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: anshul8394/user-service:latest
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
