apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: nittfest
  labels:
    app.kubernetes.io/part-of: nittfest
data:
  USER_SERVICE_URL: "http://user-service.nittfest.svc.cluster.local:8081"

